---
- name: Пошаговое создание инфраструктуры CA на РЕД ОС
  hosts: srv (ваш сервер сертификации)
  become: yes  
  vars:
    cert_dir: "/root/openssl"
    ca_passphrase: P@ssw0rd

  tasks:
    - name: 0. Установка зависимостей Python для OpenSSL
      ansible.builtin.dnf:
        name: python3-cryptography
        state: present
    - name: Подготовка удаленного сервера (установка зависимостей)
      block:
        - name: 0.1 Установка системного пакета python3-pip
          ansible.builtin.dnf:
            name: python3-pip
            state: present

        - name: 0.2 Обновление библиотеки cryptography через pip
          ansible.builtin.pip:
            name: cryptography
            state: latest

        - name: 0.3 Установка коллекции community.crypto на удаленный сервер
          ansible.builtin.shell: "ansible-galaxy collection install community.crypto"
          register: collection_install
          changed_when: "'nothing to do' not in collection_install.stdout"

    - name: 1. Создание защищенной директории
      ansible.builtin.file:
        path: "{{ cert_dir }}"
        state: directory
        mode: '0700'
        owner: root

    - name: 2. Создание приватного ключа CA (AES-128-CBC)
      community.crypto.openssl_privatekey:
        path: "{{ cert_dir }}/rootCA.key"
        passphrase: "{{ ca_passphrase }}"
        cipher: auto
        size: 2048
        type: RSA
        owner: root
        mode: '0600'

    - name: 3. Создание CSR (запроса) для сертификата CA
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ cert_dir }}/rootCA.key"
        privatekey_passphrase: "{{ ca_passphrase }}"
        common_name: "SRV.LAB.LOCAL"
        country_name: "RU"
        state_or_province_name: "Tatarstan"
        locality_name: "Almet"
        organization_name: "LAB.LOCAL"
        organizational_unit_name: "SRV"
        email_address: "postmaster@lab.local"
        digest: sha256
      register: ca_csr

    - name: 4. Создание самоподписанного сертификата CA (на 365 дней)
      community.crypto.x509_certificate:
        path: "{{ cert_dir }}/rootCA.crt"
        csr_content: "{{ ca_csr.csr }}"
        privatekey_path: "{{ cert_dir }}/rootCA.key"
        privatekey_passphrase: "{{ ca_passphrase }}"
        provider: selfsigned
        selfsigned_not_after: "+365d"
        owner: root
        mode: '0644'
        # Добавляем флаг CA, чтобы сертификат мог подписывать другие сертификаты
        basic_constraints:
          - "CA:TRUE"
        basic_constraints_critical: yes
        key_usage:
          - keyCertSign
          - cRLSign
