---
- name: Полная настройка нового сервера
  hosts: all
  become: yes
#  become_method: su  раскоментировать эти строчки в первый раз если на удалённом сервере запрещён ssh под root и нет пользователя в sudoers
#  become_user: root
#  become_flags: "-" 
  vars:
    # --- Блок настроек пользователя ---
    username: "sshuser"
    admin_group: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
    passwd: "P@ssw0rd" 
    ssh_key_path: "/home/grimm/.ssh/id_ed25519"
    # --- Блок настроек безопасности SSH ---
    ssh_port: "22"

  tasks:
    # --- РАЗДЕЛ 0: SELINUX ---
    - name: Мгновенное переключение SELinux в Permissive
      shell: setenforce 0
      when: ansible_os_family == "RedHat"
      failed_when: false

    - name: Постоянное отключение SELinux в конфиге
      selinux:
        state: disabled
      when: ansible_os_family == "RedHat"

    # --- РАЗДЕЛ 1: СОЗДАНИЕ АДМИНИСТРАТОРА ---
    - name: Создание группы и пользователя
      user:
        name: "{{ username }}"
        groups: "{{ admin_group }}"
        append: yes
        password: "{{ passwd | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Настройка sudo без пароля для нового пользователя
      lineinfile:
        path: "/etc/sudoers.d/{{ username }}"
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
        create: yes
        mode: '0440'
        
    # --- РАЗДЕЛ 2: ФАЕРВОЛ ---
    - name: Проверка наличия firewalld
      systemd:
        name: firewalld
      register: firewalld_check
      failed_when: false

    - name: Открываем новый порт SSH в Firewalld
      firewalld:
        port: "{{ ssh_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      when: 
        - firewalld_check.status is defined and firewalld_check.status.ActiveState == "active"
        - ansible_os_family == "RedHat"
      ignore_errors: yes

    # --- РАЗДЕЛ 3: ЗАЩИТА SSH ---
    - name: Генерация SSH-ключа на локальной машине
      delegate_to: localhost
      run_once: true
      openssh_keypair:
        path: "{{ ssh_key_path }}"
        type: ed25519
        state: present
        owner: user
        group: user
        mode: '0600'

    - name: Добавление ключа самому себе (localhost)
      authorized_key:
        user: grimm  # Ваше локальное имя пользователя
        state: present
        key: "{{ lookup('file', ssh_key_path + '.pub') }}"
      delegate_to: localhost

    - name: Добавление вашего SSH-ключа
      authorized_key:
        user: "{{ username }}"
        state: present
        # Важно: добавляем .pub к пути, чтобы прочитать публичную часть
        key: "{{ lookup('file', ssh_key_path + '.pub') }}"

    - name: Создать файл баннера
      copy:
        dest: /etc/ssh/banner.txt
        content: |
          **********************************************************
          Welcome to {{ inventory_hostname }}!
          Hello from {{ ansible_os_family }}.
          **********************************************************
        owner: root
        group: root
        mode: '0644'

    - name: Настройка параметров SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^#?Banner", line: "Banner /etc/ssh/banner.txt" }
        - { regexp: "^#?Port", line: "Port {{ ssh_port }}" }
        - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin no" }
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      service:
        name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
        state: restarted
