---
- name: Полная настройка нового сервера
  hosts: all
  become: yes
  vars:
    # --- Блок настроек пользователя ---
    username: "sshuser"
    admin_group: "sudo"  # Поменяйте на 'wheel' для CentOS/RHEL
    ssh_key_path: "~/.ssh/id_ed25519.pub"
    #запускать ansible-playbook ssh.yml -u root --ask-pass
    # --- Блок настроек безопасности SSH ---
    ssh_port: "2222"     # Новый порт SSH (выберите свой)

  tasks:
    - name: Генерация SSH-ключа на локальной машине
      delegate_to: localhost
      run_once: true
      openssh_keypair:
        path: "~/.ssh/id_ed25519"
        type: ed25519
        state: present

    # --- РАЗДЕЛ 1: СОЗДАНИЕ АДМИНИСТРАТОРА ---
    - name: Создание группы и пользователя
      user:
        name: "{{ username }}"
        groups: "{{ admin_group }}"
        append: yes
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Добавление вашего SSH-ключа
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', ssh_key_path) }}"

    - name: Настройка sudo без пароля для нового пользователя
      lineinfile:
        path: "/etc/sudoers.d/{{ username }}"
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
        create: yes
        mode: '0440'

    # --- РАЗДЕЛ 2: ЗАЩИТА SSH ---
    - name: Настройка параметров SSH (порт, запрет паролей, запрет root)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^#?Port", line: "Port {{ ssh_port }}" }
        - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin no" }
        - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication no" }
      notify: Restart SSH

    # --- РАЗДЕЛ 3: ФАЕРВОЛ (UFW) ---
#    - name: Разрешаем новый порт SSH в фаерволе
#      ufw:
#        rule: allow
#        port: "{{ ssh_port }}"
#        proto: tcp

#    - name: Включаем фаервол (UFW)
#      ufw:
#        state: enabled
#        policy: deny # Запрещаем всё, что не разрешено явно

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

